### ISSUE TITLE
npm install fails with recent versions of node

### ISSUE THREAD

**Issue by lexoyo** [alqh/meta-release#5]
Hello @alqh ,

I may be able to fix this, but first I'd like to see if you are responding / accepting PRs and if you have pointers ?

The install with node 10 works, but here is the problem with recent nodejs versions: 

```
$ node -v
v18.13.0
$ npm install --save meta-release
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c -- node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! Failed to execute '/home/lexoyo/.nvm/versions/node/v18.13.0/bin/node /home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp info
npm ERR! using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@18.13.0 | linux | x64
npm ERR! node-pre-gyp
npm ERR! 
npm ERR! WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check
npm ERR! checked for "/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v108-linux-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.5 and node@18.13.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v108-linux-x64.tar.gz
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@9.1.0
npm ERR! gyp info using node@18.13.0 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! 
npm ERR! using node-gyp@9.1.0
npm ERR! gyp info using node@18.13.0 | linux | x64
npm ERR! gyp
npm ERR! info find Python using Python version 3.10.8 found at "/usr/bin/python3"
npm ERR! gyp info
npm ERR! spawn /usr/bin/python3
npm ERR! gyp info
npm ERR! spawn args [
npm ERR! gyp info spawn args   '/home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info
npm ERR! spawn args   '-f',
npm ERR! gyp
npm ERR! info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/lexoyo/.cache/node-gyp/18.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args
npm ERR! '-Dnode_root_dir=/home/lexoyo/.cache/node-gyp/18.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info
npm ERR! spawn args   '-Dnode_lib_file=/home/lexoyo/.cache/node-gyp/18.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit',
npm ERR! gyp info
npm ERR! spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: line 1: krb5-config: command not found
npm ERR! gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp
npm ERR! ERR! configure error
npm ERR! gyp ERR!
npm ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
npm ERR! gyp
npm ERR! ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR!
npm ERR! System Linux 6.0.12-100.fc35.x86_64
npm ERR! gyp
npm ERR! ERR! command "/home/lexoyo/.nvm/versions/node/v18.13.0/bin/node" "/home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp
npm ERR! ERR! cwd /home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit
npm ERR! gyp ERR! node -v
npm ERR! v18.13.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp
npm ERR! ERR! build error
npm ERR! node-pre-gyp ERR!
npm ERR! stack Error: Failed to execute '/home/lexoyo/.nvm/versions/node/v18.13.0/bin/node /home/lexoyo/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR!
npm ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR!
npm ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR!
npm ERR! System Linux 6.0.12-100.fc35.x86_64
npm ERR! node-pre-gyp ERR! command "/home/lexoyo/.nvm/versions/node/v18.13.0/bin/node" "/home/lexoyo/Documents/silex/silex-meta-v3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/lexoyo/Documents/silex/silex-meta-v3/node_modules/nodegit
npm ERR! node-pre-gyp ERR! node -v v18.13.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR!
npm ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lexoyo/.npm/_logs/2023-02-04T18_46_25_864Z-debug-0.log
```

**Comment by lexoyo** [comment]
I ended up using yarn/npm workspaces like this
https://github.com/silexlabs/silex-meta
